export const cards = [
    {
        id: 1,
        title: "Life lessons with Katie Zaferes",
        description: "I will share with you what I call \"Positively Impactful Moments of Disappointment.\" Throughout my career, many of my highest moments only came after setbacks and losses. But learning from those difficult moments is what gave me the ability to rise above them and reach my goals.",
        img: "katie-zaferes.png",
        rating: '5.0',
        reviews: 6,
        country: "USA",
        location: "online",
        price: 136,
        openSpots: 0,
    },
    {
        id: 2,
        title: "Learn Wedding Photography",
        description: "Interested in becoming a wedding photographer? For beginner and experienced photographers alike, join us in learning techniques required to leave the happy couple with memories that'll last a lifetime.",
        img: "wedding-photography.png",
        rating: '5.0',
        reviews: 30,
        country: "USA",
        location: "online",
        price: 125,
        openSpots: 27,
    },
    {
        id: 3,
        title: "Group Mountain Biking",
        description: "Experience the beautiful Norwegian landscape and meet new friends all while conquering rugged terrain on your mountain bike. (Bike provided!)",
        img: "mountain-bike.png",
        rating: '4.8',
        reviews: 2,
        country: "Norway",
        location: "real",
        price: 50,
        openSpots: 3,
    },
]